[package]
name = "entities"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gen-entities = { path = "gen-entities" }
lazy_static = "1.5.0"
memchr = "2.7.4"
