#![allow(non_camel_case_types)]

use std::{fmt::Display, rc::Rc};

#[derive(Debug, Clone)]
pub enum TagName {
    A,
    ADDRESS,
    APPLET,
    AREA,
    ARTICLE,
    ASIDE,
    B,
    BASE,
    BASEFONT,
    BGSOUND,
    BIG,
    BLOCKQUOTE,
    BODY,
    BR,
    BUTTON,
    CAPTION,
    CENTER,
    CODE,
    COL,
    COLGROUP,
    DD,
    DETAILS,
    DIALOG,
    DIR,
    DIV,
    DL,
    DT,
    EM,
    EMBED,
    FIELDSET,
    FIGCAPTION,
    FIGURE,
    FONT,
    FOOTER,
    FORM,
    FRAME,
    FRAMESET,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    HEAD,
    HEADER,
    HGROUP,
    HR,
    HTML,
    I,
    IFRAME,
    IMG,
    INPUT,
    KEYGEN,
    LI,
    LINK,
    LISTING,
    MAIN,
    MARQUEE,
    MENU,
    META,
    NAV,
    NOBR,
    NOEMBED,
    NOFRAMES,
    NOSCRIPT,
    OBJECT,
    OL,
    OPTGROUP,
    OPTION,
    P,
    PARAM,
    PLAINTEXT,
    PRE,
    RB,
    RP,
    RT,
    RTC,
    RUBY,
    S,
    SCRIPT,
    SEARCH,
    SECTION,
    SELECT,
    SMALL,
    SOURCE,
    SPAN,
    STRIKE,
    STRONG,
    STYLE,
    SUB,
    SUMMARY,
    SUP,
    TABLE,
    TBODY,
    TD,
    TEMPLATE,
    TEXTAREA,
    TFOOT,
    TH,
    THEAD,
    TITLE,
    TR,
    TRACK,
    TT,
    U,
    UL,
    VAR,
    WBR,
    XMP,

    // MathML tags we're interested in
    // @todo add arbitrary mathml tag
    MATH,
    ANNOTATION_XML,
    MALIGNMARK,
    MGLYPH,
    MI,
    MN,
    MO,
    MS,
    MTEXT,

    // SVG tags we're interested in
    // @todo add arbitrary svg tag
    SVG,
    FOREIGNOBJECT,
    DESC,

    // Arbitrary tag names not listed here, e.g. <custom-tag>
    Arbitrary(Rc<[u8]>),
}

impl From<&[u8]> for TagName {
    fn from(value: &[u8]) -> Self {
        let upper_cased = value.to_ascii_uppercase();
        match upper_cased.as_slice() {
            b"A" => Self::A,
            b"ADDRESS" => Self::ADDRESS,
            b"APPLET" => Self::APPLET,
            b"AREA" => Self::AREA,
            b"ARTICLE" => Self::ARTICLE,
            b"ASIDE" => Self::ASIDE,
            b"B" => Self::B,
            b"BASE" => Self::BASE,
            b"BASEFONT" => Self::BASEFONT,
            b"BGSOUND" => Self::BGSOUND,
            b"BIG" => Self::BIG,
            b"BLOCKQUOTE" => Self::BLOCKQUOTE,
            b"BODY" => Self::BODY,
            b"BR" => Self::BR,
            b"BUTTON" => Self::BUTTON,
            b"CAPTION" => Self::CAPTION,
            b"CENTER" => Self::CENTER,
            b"CODE" => Self::CODE,
            b"COL" => Self::COL,
            b"COLGROUP" => Self::COLGROUP,
            b"DD" => Self::DD,
            b"DETAILS" => Self::DETAILS,
            b"DIALOG" => Self::DIALOG,
            b"DIR" => Self::DIR,
            b"DIV" => Self::DIV,
            b"DL" => Self::DL,
            b"DT" => Self::DT,
            b"EM" => Self::EM,
            b"EMBED" => Self::EMBED,
            b"FIELDSET" => Self::FIELDSET,
            b"FIGCAPTION" => Self::FIGCAPTION,
            b"FIGURE" => Self::FIGURE,
            b"FONT" => Self::FONT,
            b"FOOTER" => Self::FOOTER,
            b"FORM" => Self::FORM,
            b"FRAME" => Self::FRAME,
            b"FRAMESET" => Self::FRAMESET,
            b"H1" => Self::H1,
            b"H2" => Self::H2,
            b"H3" => Self::H3,
            b"H4" => Self::H4,
            b"H5" => Self::H5,
            b"H6" => Self::H6,
            b"HEAD" => Self::HEAD,
            b"HEADER" => Self::HEADER,
            b"HGROUP" => Self::HGROUP,
            b"HR" => Self::HR,
            b"HTML" => Self::HTML,
            b"I" => Self::I,
            b"IFRAME" => Self::IFRAME,
            b"IMG" => Self::IMG,
            b"INPUT" => Self::INPUT,
            b"KEYGEN" => Self::KEYGEN,
            b"LI" => Self::LI,
            b"LINK" => Self::LINK,
            b"LISTING" => Self::LISTING,
            b"MAIN" => Self::MAIN,
            b"MARQUEE" => Self::MARQUEE,
            b"MENU" => Self::MENU,
            b"META" => Self::META,
            b"NAV" => Self::NAV,
            b"NOBR" => Self::NOBR,
            b"NOEMBED" => Self::NOEMBED,
            b"NOFRAMES" => Self::NOFRAMES,
            b"NOSCRIPT" => Self::NOSCRIPT,
            b"OBJECT" => Self::OBJECT,
            b"OL" => Self::OL,
            b"OPTGROUP" => Self::OPTGROUP,
            b"OPTION" => Self::OPTION,
            b"P" => Self::P,
            b"PARAM" => Self::PARAM,
            b"PLAINTEXT" => Self::PLAINTEXT,
            b"PRE" => Self::PRE,
            b"RB" => Self::RB,
            b"RP" => Self::RP,
            b"RT" => Self::RT,
            b"RTC" => Self::RTC,
            b"RUBY" => Self::RUBY,
            b"S" => Self::S,
            b"SCRIPT" => Self::SCRIPT,
            b"SEARCH" => Self::SEARCH,
            b"SECTION" => Self::SECTION,
            b"SELECT" => Self::SELECT,
            b"SMALL" => Self::SMALL,
            b"SOURCE" => Self::SOURCE,
            b"SPAN" => Self::SPAN,
            b"STRIKE" => Self::STRIKE,
            b"STRONG" => Self::STRONG,
            b"STYLE" => Self::STYLE,
            b"SUB" => Self::SUB,
            b"SUMMARY" => Self::SUMMARY,
            b"SUP" => Self::SUP,
            b"TABLE" => Self::TABLE,
            b"TBODY" => Self::TBODY,
            b"TD" => Self::TD,
            b"TEMPLATE" => Self::TEMPLATE,
            b"TEXTAREA" => Self::TEXTAREA,
            b"TFOOT" => Self::TFOOT,
            b"TH" => Self::TH,
            b"THEAD" => Self::THEAD,
            b"TITLE" => Self::TITLE,
            b"TR" => Self::TR,
            b"TRACK" => Self::TRACK,
            b"TT" => Self::TT,
            b"U" => Self::U,
            b"UL" => Self::UL,
            b"VAR" => Self::VAR,
            b"WBR" => Self::WBR,
            b"XMP" => Self::XMP,

            b"SVG" => Self::SVG,
            b"DESC" => Self::DESC,
            b"FOREIGNOBJECT" => Self::FOREIGNOBJECT,

            b"MATH" => Self::MATH,
            b"ANNOTATION-XML" => Self::ANNOTATION_XML,
            b"MALIGNMARK" => Self::MALIGNMARK,
            b"MGLYPH" => Self::MGLYPH,
            b"MI" => Self::MI,
            b"MN" => Self::MN,
            b"MO" => Self::MO,
            b"MS" => Self::MS,
            b"MTEXT" => Self::MTEXT,

            _ => Self::Arbitrary(value.into()),
        }
    }
}

impl Into<Box<[u8]>> for TagName {
    fn into(self) -> Box<[u8]> {
        match self {
            TagName::A => b"A".as_slice(),
            TagName::ADDRESS => b"ADDRESS".as_slice(),
            TagName::APPLET => b"APPLET".as_slice(),
            TagName::AREA => b"AREA".as_slice(),
            TagName::ARTICLE => b"ARTICLE".as_slice(),
            TagName::ASIDE => b"ASIDE".as_slice(),
            TagName::B => b"B".as_slice(),
            TagName::BASE => b"BASE".as_slice(),
            TagName::BASEFONT => b"BASEFONT".as_slice(),
            TagName::BGSOUND => b"BGSOUND".as_slice(),
            TagName::BIG => b"BIG".as_slice(),
            TagName::BLOCKQUOTE => b"BLOCKQUOTE".as_slice(),
            TagName::BODY => b"BODY".as_slice(),
            TagName::BR => b"BR".as_slice(),
            TagName::BUTTON => b"BUTTON".as_slice(),
            TagName::CAPTION => b"CAPTION".as_slice(),
            TagName::CENTER => b"CENTER".as_slice(),
            TagName::CODE => b"CODE".as_slice(),
            TagName::COL => b"COL".as_slice(),
            TagName::COLGROUP => b"COLGROUP".as_slice(),
            TagName::DD => b"DD".as_slice(),
            TagName::DETAILS => b"DETAILS".as_slice(),
            TagName::DIALOG => b"DIALOG".as_slice(),
            TagName::DIR => b"DIR".as_slice(),
            TagName::DIV => b"DIV".as_slice(),
            TagName::DL => b"DL".as_slice(),
            TagName::DT => b"DT".as_slice(),
            TagName::EM => b"EM".as_slice(),
            TagName::EMBED => b"EMBED".as_slice(),
            TagName::FIELDSET => b"FIELDSET".as_slice(),
            TagName::FIGCAPTION => b"FIGCAPTION".as_slice(),
            TagName::FIGURE => b"FIGURE".as_slice(),
            TagName::FONT => b"FONT".as_slice(),
            TagName::FOOTER => b"FOOTER".as_slice(),
            TagName::FORM => b"FORM".as_slice(),
            TagName::FRAME => b"FRAME".as_slice(),
            TagName::FRAMESET => b"FRAMESET".as_slice(),
            TagName::H1 => b"H1".as_slice(),
            TagName::H2 => b"H2".as_slice(),
            TagName::H3 => b"H3".as_slice(),
            TagName::H4 => b"H4".as_slice(),
            TagName::H5 => b"H5".as_slice(),
            TagName::H6 => b"H6".as_slice(),
            TagName::HEAD => b"HEAD".as_slice(),
            TagName::HEADER => b"HEADER".as_slice(),
            TagName::HGROUP => b"HGROUP".as_slice(),
            TagName::HR => b"HR".as_slice(),
            TagName::HTML => b"HTML".as_slice(),
            TagName::I => b"I".as_slice(),
            TagName::IFRAME => b"IFRAME".as_slice(),
            TagName::IMG => b"IMG".as_slice(),
            TagName::INPUT => b"INPUT".as_slice(),
            TagName::KEYGEN => b"KEYGEN".as_slice(),
            TagName::LI => b"LI".as_slice(),
            TagName::LINK => b"LINK".as_slice(),
            TagName::LISTING => b"LISTING".as_slice(),
            TagName::MAIN => b"MAIN".as_slice(),
            TagName::MARQUEE => b"MARQUEE".as_slice(),
            TagName::MENU => b"MENU".as_slice(),
            TagName::META => b"META".as_slice(),
            TagName::NAV => b"NAV".as_slice(),
            TagName::NOBR => b"NOBR".as_slice(),
            TagName::NOEMBED => b"NOEMBED".as_slice(),
            TagName::NOFRAMES => b"NOFRAMES".as_slice(),
            TagName::NOSCRIPT => b"NOSCRIPT".as_slice(),
            TagName::OBJECT => b"OBJECT".as_slice(),
            TagName::OL => b"OL".as_slice(),
            TagName::OPTGROUP => b"OPTGROUP".as_slice(),
            TagName::OPTION => b"OPTION".as_slice(),
            TagName::P => b"P".as_slice(),
            TagName::PARAM => b"PARAM".as_slice(),
            TagName::PLAINTEXT => b"PLAINTEXT".as_slice(),
            TagName::PRE => b"PRE".as_slice(),
            TagName::RB => b"RB".as_slice(),
            TagName::RP => b"RP".as_slice(),
            TagName::RT => b"RT".as_slice(),
            TagName::RTC => b"RTC".as_slice(),
            TagName::RUBY => b"RUBY".as_slice(),
            TagName::S => b"S".as_slice(),
            TagName::SCRIPT => b"SCRIPT".as_slice(),
            TagName::SEARCH => b"SEARCH".as_slice(),
            TagName::SECTION => b"SECTION".as_slice(),
            TagName::SELECT => b"SELECT".as_slice(),
            TagName::SMALL => b"SMALL".as_slice(),
            TagName::SOURCE => b"SOURCE".as_slice(),
            TagName::SPAN => b"SPAN".as_slice(),
            TagName::STRIKE => b"STRIKE".as_slice(),
            TagName::STRONG => b"STRONG".as_slice(),
            TagName::STYLE => b"STYLE".as_slice(),
            TagName::SUB => b"SUB".as_slice(),
            TagName::SUMMARY => b"SUMMARY".as_slice(),
            TagName::SUP => b"SUP".as_slice(),
            TagName::TABLE => b"TABLE".as_slice(),
            TagName::TBODY => b"TBODY".as_slice(),
            TagName::TD => b"TD".as_slice(),
            TagName::TEMPLATE => b"TEMPLATE".as_slice(),
            TagName::TEXTAREA => b"TEXTAREA".as_slice(),
            TagName::TFOOT => b"TFOOT".as_slice(),
            TagName::TH => b"TH".as_slice(),
            TagName::THEAD => b"THEAD".as_slice(),
            TagName::TITLE => b"TITLE".as_slice(),
            TagName::TR => b"TR".as_slice(),
            TagName::TRACK => b"TRACK".as_slice(),
            TagName::TT => b"TT".as_slice(),
            TagName::U => b"U".as_slice(),
            TagName::UL => b"UL".as_slice(),
            TagName::VAR => b"VAR".as_slice(),
            TagName::WBR => b"WBR".as_slice(),
            TagName::XMP => b"XMP".as_slice(),

            TagName::MATH => b"MATH".as_slice(),
            TagName::ANNOTATION_XML => b"ANNOTATION-XML".as_slice(),
            TagName::MALIGNMARK => b"MALIGNMARK".as_slice(),
            TagName::MGLYPH => b"MGLYPH".as_slice(),
            TagName::MI => b"MI".as_slice(),
            TagName::MN => b"MN".as_slice(),
            TagName::MO => b"MO".as_slice(),
            TagName::MS => b"MS".as_slice(),
            TagName::MTEXT => b"MTEXT".as_slice(),

            TagName::SVG => b"SVG".as_slice(),
            TagName::DESC => b"DESC".as_slice(),
            TagName::FOREIGNOBJECT => b"FOREIGNOBJECT".as_slice(),

            TagName::Arbitrary(arbitrary_name) => return Box::from(arbitrary_name.as_ref()),
        }
        .into()
    }
}

impl PartialEq<Self> for TagName {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Arbitrary(a), Self::Arbitrary(b)) => a.eq_ignore_ascii_case(b),
            (a, b) => a == b,
        }
    }
}

impl Display for TagName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Arbitrary(name) => {
                write!(f, "Arbitrary({})", String::from_utf8_lossy(name))
            }
            _ => write!(f, "{:?}", self),
        }
    }
}
