use std::rc::Rc;

#[derive(Debug, PartialEq, Clone)]
pub enum TagName {
    A,
    ADDRESS,
    APPLET,
    AREA,
    ARTICLE,
    ASIDE,
    B,
    BASE,
    BASEFONT,
    BGSOUND,
    BIG,
    BLOCKQUOTE,
    BODY,
    BR,
    BUTTON,
    CAPTION,
    CENTER,
    CODE,
    COL,
    COLGROUP,
    DD,
    DETAILS,
    DIALOG,
    DIR,
    DIV,
    DL,
    DT,
    EM,
    EMBED,
    FIELDSET,
    FIGCAPTION,
    FIGURE,
    FONT,
    FOOTER,
    FORM,
    FRAME,
    FRAMESET,
    HEAD,
    HEADER,
    HGROUP,
    HR,
    HTML,
    I,
    IFRAME,
    IMAGE,
    IMG,
    INPUT,
    KEYGEN,
    LI,
    LINK,
    LISTING,
    MAIN,
    MARQUEE,
    MATH,
    MENU,
    META,
    NAV,
    NOBR,
    NOEMBED,
    NOFRAMES,
    NOSCRIPT,
    OBJECT,
    OL,
    OPTGROUP,
    OPTION,
    P,
    PARAM,
    PLAINTEXT,
    PRE,
    RB,
    RP,
    RT,
    RTC,
    RUBY,
    S,
    SCRIPT,
    SEARCH,
    SECTION,
    SELECT,
    SMALL,
    SOURCE,
    SPAN,
    STRIKE,
    STRONG,
    STYLE,
    SUB,
    SUMMARY,
    SUP,
    SVG,
    TABLE,
    TBODY,
    TD,
    TEMPLATE,
    TEXTAREA,
    TFOOT,
    TH,
    THEAD,
    TITLE,
    TR,
    TRACK,
    TT,
    U,
    UL,
    VAR,
    WBR,
    XMP,
    Doctype,
    Custom(Rc<[u8]>),
}

impl From<&[u8]> for TagName {
    fn from(value: &[u8]) -> Self {
        match value.to_ascii_uppercase().as_slice() {
            b"A" => Self::A,
            b"ADDRESS" => Self::ADDRESS,
            b"APPLET" => Self::APPLET,
            b"AREA" => Self::AREA,
            b"ARTICLE" => Self::ARTICLE,
            b"ASIDE" => Self::ASIDE,
            b"B" => Self::B,
            b"BASE" => Self::BASE,
            b"BASEFONT" => Self::BASEFONT,
            b"BGSOUND" => Self::BGSOUND,
            b"BIG" => Self::BIG,
            b"BLOCKQUOTE" => Self::BLOCKQUOTE,
            b"BODY" => Self::BODY,
            b"BR" => Self::BR,
            b"BUTTON" => Self::BUTTON,
            b"CAPTION" => Self::CAPTION,
            b"CENTER" => Self::CENTER,
            b"CODE" => Self::CODE,
            b"COL" => Self::COL,
            b"COLGROUP" => Self::COLGROUP,
            b"DD" => Self::DD,
            b"DETAILS" => Self::DETAILS,
            b"DIALOG" => Self::DIALOG,
            b"DIR" => Self::DIR,
            b"DIV" => Self::DIV,
            b"DL" => Self::DL,
            b"DT" => Self::DT,
            b"EM" => Self::EM,
            b"EMBED" => Self::EMBED,
            b"FIELDSET" => Self::FIELDSET,
            b"FIGCAPTION" => Self::FIGCAPTION,
            b"FIGURE" => Self::FIGURE,
            b"FONT" => Self::FONT,
            b"FOOTER" => Self::FOOTER,
            b"FORM" => Self::FORM,
            b"FRAME" => Self::FRAME,
            b"FRAMESET" => Self::FRAMESET,
            b"HEAD" => Self::HEAD,
            b"HEADER" => Self::HEADER,
            b"HGROUP" => Self::HGROUP,
            b"HR" => Self::HR,
            b"HTML" => Self::HTML,
            b"I" => Self::I,
            b"IFRAME" => Self::IFRAME,
            b"IMAGE" => Self::IMAGE,
            b"IMG" => Self::IMG,
            b"INPUT" => Self::INPUT,
            b"KEYGEN" => Self::KEYGEN,
            b"LI" => Self::LI,
            b"LINK" => Self::LINK,
            b"LISTING" => Self::LISTING,
            b"MAIN" => Self::MAIN,
            b"MARQUEE" => Self::MARQUEE,
            b"MATH" => Self::MATH,
            b"MENU" => Self::MENU,
            b"META" => Self::META,
            b"NAV" => Self::NAV,
            b"NOBR" => Self::NOBR,
            b"NOEMBED" => Self::NOEMBED,
            b"NOFRAMES" => Self::NOFRAMES,
            b"NOSCRIPT" => Self::NOSCRIPT,
            b"OBJECT" => Self::OBJECT,
            b"OL" => Self::OL,
            b"OPTGROUP" => Self::OPTGROUP,
            b"OPTION" => Self::OPTION,
            b"P" => Self::P,
            b"PARAM" => Self::PARAM,
            b"PLAINTEXT" => Self::PLAINTEXT,
            b"PRE" => Self::PRE,
            b"RB" => Self::RB,
            b"RP" => Self::RP,
            b"RT" => Self::RT,
            b"RTC" => Self::RTC,
            b"RUBY" => Self::RUBY,
            b"S" => Self::S,
            b"SCRIPT" => Self::SCRIPT,
            b"SEARCH" => Self::SEARCH,
            b"SECTION" => Self::SECTION,
            b"SELECT" => Self::SELECT,
            b"SMALL" => Self::SMALL,
            b"SOURCE" => Self::SOURCE,
            b"SPAN" => Self::SPAN,
            b"STRIKE" => Self::STRIKE,
            b"STRONG" => Self::STRONG,
            b"STYLE" => Self::STYLE,
            b"SUB" => Self::SUB,
            b"SUMMARY" => Self::SUMMARY,
            b"SUP" => Self::SUP,
            b"SVG" => Self::SVG,
            b"TABLE" => Self::TABLE,
            b"TBODY" => Self::TBODY,
            b"TD" => Self::TD,
            b"TEMPLATE" => Self::TEMPLATE,
            b"TEXTAREA" => Self::TEXTAREA,
            b"TFOOT" => Self::TFOOT,
            b"TH" => Self::TH,
            b"THEAD" => Self::THEAD,
            b"TITLE" => Self::TITLE,
            b"TR" => Self::TR,
            b"TRACK" => Self::TRACK,
            b"TT" => Self::TT,
            b"U" => Self::U,
            b"UL" => Self::UL,
            b"VAR" => Self::VAR,
            b"WBR" => Self::WBR,
            b"XMP" => Self::XMP,
            _ => Self::Custom(value.into()),
        }
    }
}
