[package]
name = "wp-html-api"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]

[dependencies]
entities = { path = "../entities" }

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
